services:
  flask-redis:
    build: .
    ports:
      - 5000:5000
    container_name: flask-redis
    depends_on: 
      - redis
    volumes:
      - flask-redis-vol:/app/env/Lib/site-packages
  redis :
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: rdb
    volumes:
      - redis-vol:/data
volumes:
  redis-vol: 
  flask-redis-vol:
